### ISSUE TITLE
Mime type not recognized for Javascript files after ajax request

### ISSUE THREAD

**Issue by luisnegrete-vungle** [eclipse-ee4j/mojarra#4880] opened 2021-03-29 11:44 UTC
Loading a Javascript file using the h:outputScript tag and setting the target property to head results in the following warning in the logs:

[#|2020-12-06T03:57:42.882+0000|WARNING|Payara 5.192|javax.enterprise.resource.webcontainer.jsf.context|_ThreadID=29;_ThreadName=http-thread-pool::http-listener-1(5);_TimeMillis=1607227062882;_LevelValue=900;_MessageID=jsf.externalcontext.no.mime.type.found;| JSF1091: No mime type could be found for file . To resolve this, add a mime-type mapping to the applications web.xml.|#]. The bug seems to be happening due to the file being processed as empty in the ExternalContextWrapperImpl used by Faces. This can be debugged using a custom wrapper:

`import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.faces.FacesException;
import javax.faces.FacesWrapper;
import javax.faces.context.ExternalContext;
import javax.faces.context.ExternalContextFactory;
import javax.faces.context.ExternalContextWrapper;
import javax.servlet.http.HttpServletRequest;

public class CustomFacesContextFactory extends ExternalContextFactory implements FacesWrapper<ExternalContextFactory>
{
	private static final Logger log = LoggerFactory.getLogger(CustomFacesContextFactory.class);
	
	private ExternalContextFactory factory;
	
	private static final class ExternalContextWrapperImpl extends ExternalContextWrapper
	{
		private ExternalContext externalContext;
		
		public ExternalContextWrapperImpl(ExternalContext externalContext) {
			super();
			this.externalContext = externalContext;
		}
		
		@Override
		public String getMimeType(String file)
		{
                        //Note that file name is coming as empty for JS files 
			log.debug("Getting mime type for file {}", file);
			String mimeType;
			
			if (file != null && file.endsWith(".ecss"))
			{
				mimeType = "text/plain";
			}
			
			else
			{
				mimeType = super.getMimeType(file);
			}
			
			if(Strings.isNullOrEmpty(mimeType))
			{
				HttpServletRequest request = (HttpServletRequest)externalContext.getRequest();
				mimeType = super.getMimeType(FileUtil.getFileNameFromURL(request.getRequestURL().toString()));
			}
			//externalContext.getRequest()
			log.debug("Returning mime type {}", mimeType);
			return mimeType;
		}
		
		@Override
		public ExternalContext getWrapped() {
			return externalContext;
		}
		
		@Override
		public boolean isSecure() {
			return getWrapped().isSecure();
		}
	}
	
	public CustomFacesContextFactory(ExternalContextFactory factory) {
		super();
		this.factory = factory;
	}
	
	@Override
	public ExternalContextFactory getWrapped() {
		return factory;
	}
	
	@Override
	public ExternalContext getExternalContext(Object context, Object request, Object response) throws FacesException {
		ExternalContext externalContext = factory.getExternalContext(context, request, response);
		
		return wrap(externalContext);
	}
	
	private ExternalContext wrap(ExternalContext externalContext) {
		return new ExternalContextWrapperImpl(externalContext);
	}
}`

Mojarra Version: 2.3

**Comment by BalusC** [comment] 2021-04-15 11:01
Norepro with this:
```
<!DOCTYPE html>
<html xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head />
    <h:body>
        <h:outputScript name="script.js" target="head" />
        <h:form><h:commandButton><f:ajax/></h:commandButton></h:form>
    </h:body>
</html>
```
Please provide a reproducer.

**Comment by melloware** [comment] 2022-01-05 19:21
@BalusC we are getting this in Jboss 7.4 using Mojarra 2.3.

```
15:55:52,854 WARNING [javax.enterprise.resource.webcontainer.jsf.context] (default task-2) JSF1091: No mime type could be found for file null.  To resolve this, add a mime-type mapping to the applications web.xml.
```

Its happening using our PrimeFaces `p:poll` calls and its consistent on most of our p:poll calls.  Let me see if I can create a reproducer.

**Comment by BalusC** [comment] 2022-02-20 15:03
Still norepro.

With the `<p:poll>` sample I get `/test.xhtml`, `/jquery.js`, `/jquery-plugins.js` and `/core.js` as `file` argument, not `null` or an empty string as indicated by the warning messages. Try putting a breakpoint on `ExternalContextImpl#getMimeType()`. It  should help you in understanding where exactly that empty/null `file` is coming from.

**Comment by melloware** [comment] 2022-02-20 16:44
OK i couldn't reproduce standalone Mojarra but its happening in our WildFly so i wonder if this is something Jboss patched by hand that is not in the main fork. They have been known to do that before. :)

**Comment by BalusC** [comment] 2022-05-29 15:04
Norepro, closing off.

**Closed by BalusC** 2022-05-29 15:04 UTC
Labels: 2.3
