### ISSUE TITLE
Websocket PushContext not working anymore after application redeploy

### ISSUE THREAD

**Issue by DennisBayer** [eclipse-ee4j/mojarra#4572] opened 2019-05-16 08:26 UTC
Hi there,

in relation to [the bug filed JavaserverFaces Mojarra](https://github.com/javaserverfaces/mojarra/issues/4368) I'd like to transition it in the new repository.

@zonia3000 wrote:
> Hi,
> I'm trying the new JSF features.
> I used this example on GlassFish 5 (build 25):
> https://github.com/hantsy/ee8-sandbox/tree/master/jsf-websocket
> 
> At the first deploy all is working fine, but if I undeploy the application and then redeploy it, the push messages are no longer sent. No exception is thrown during the call of the method `push.send("msg")`, however I noticed this exception during the reload:
> 
> ```
> TRACE:   WELD-001545: MethodHandler processing call to protected void com.sun.faces.push.WebsocketSessionManager.deregister(java.lang.Iterable) for class com.sun.faces.push.WebsocketSessionManager$Proxy$_$$_WeldClientProxy
> ERROR:   WELD-000019: Error destroying an instance com.sun.faces.push.WebsocketChannelManager$ViewScope@57f59f4b of Managed Bean [class com.sun.faces.push.WebsocketChannelManager$ViewScope] with qualifiers [@Any @Default]
> DEBUG:   Catching
> org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke protected void com.sun.faces.push.WebsocketChannelManager$ViewScope.deregisterViewScope() on com.sun.faces.push.WebsocketChannelManager$ViewScope@57f59f4b
> 	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
> 	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.preDestroy(DefaultLifecycleCallbackInvoker.java:76)
> 	at org.jboss.weld.injection.producer.BasicInjectionTarget.preDestroy(BasicInjectionTarget.java:127)
> 	at org.jboss.weld.bean.ManagedBean.destroy(ManagedBean.java:192)
> 	at com.sun.faces.application.view.ViewScopeContextManager.destroyBeans(ViewScopeContextManager.java:178)
> 	at com.sun.faces.application.view.ViewScopeContextManager.sessionDestroyed(ViewScopeContextManager.java:380)
> 	at com.sun.faces.application.view.ViewScopeManager.sessionDestroyed(ViewScopeManager.java:369)
> 	at com.sun.faces.application.WebappLifecycleListener.sessionDestroyed(WebappLifecycleListener.java:241)
> 	at com.sun.faces.config.ConfigureListener.sessionDestroyed(ConfigureListener.java:435)
> 	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:867)
> 	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:811)
> 	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:799)
> 	at org.apache.catalina.session.StandardManager.stop(StandardManager.java:896)
> 	at org.apache.catalina.core.StandardContext.stop(StandardContext.java:5817)
> 	at com.sun.enterprise.web.WebModule.stop(WebModule.java:569)
> 	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:1048)
> 	at com.sun.enterprise.web.WebContainer.unloadWebModule(WebContainer.java:2197)
> 	at com.sun.enterprise.web.WebContainer.unloadWebModule(WebContainer.java:2152)
> 	at com.sun.enterprise.web.WebApplication.stop(WebApplication.java:158)
> 	at org.glassfish.internal.data.EngineRef.stop(EngineRef.java:161)
> 	at org.glassfish.internal.data.ModuleInfo.stop(ModuleInfo.java:324)
> 	at org.glassfish.internal.data.ApplicationInfo.stop(ApplicationInfo.java:380)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1059)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:2127)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:113)
> 	at com.sun.enterprise.v3.server.ApplicationConfigListener.disableApplication(ApplicationConfigListener.java:311)
> 	at com.sun.enterprise.v3.server.ApplicationConfigListener.handleAppEnableChange(ApplicationConfigListener.java:208)
> 	at com.sun.enterprise.v3.server.ApplicationConfigListener.transactionCommited(ApplicationConfigListener.java:166)
> 	at org.jvnet.hk2.config.Transactions$TransactionListenerJob.process(Transactions.java:366)
> 	at org.jvnet.hk2.config.Transactions$TransactionListenerJob.process(Transactions.java:357)
> 	at org.jvnet.hk2.config.Transactions$ListenerNotifier$1.call(Transactions.java:214)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.jvnet.hk2.config.Transactions$Notifier$1$1.run(Transactions.java:168)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
> 	... 37 more
> Caused by: org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.ApplicationScoped
> 	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:623)
> 	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
> 	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:123)
> 	at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
> 	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
> 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:99)
> 	at com.sun.faces.push.WebsocketSessionManager$Proxy$_$$_WeldClientProxy.deregister(Unknown Source)
> 	at com.sun.faces.push.WebsocketChannelManager$ViewScope.deregisterViewScope(WebsocketChannelManager.java:213)
> 	... 42 more
> ```
> 
> I have to restart the server in order to have websockets working again.

**Comment by DennisBayer** [comment] 2019-05-16 08:28
I also can confirm this behavior for ```[org.jboss.as] WFLYSRV0049: JBoss EAP 7.2.0.GA (WildFly Core 6.0.11.Final-redhat-00001)```.

@BalusC I noticed you did the majority for the push integration. Do you have any clues on this?

Regards

PS: I apologize for the second mention in any case you're disturbed by the notification.

**Comment by BalusC** [comment] 2019-05-21 15:47
The stack trace reveals a bug in Weld implementation being used in particular GlassFish version. But nonetheless you need to enable session persistence. I.e. the server must be instructed to persist sessions during restart/redeploy. Yours isn't. Continuing websockets after restart/redeploy works only when session persistence is enabled in server.

**Comment by DennisBayer** [comment] 2019-05-24 06:36
Hi BalusC,

thanks for your response. I was wondering about the whole session persistence and I took a look at the linked example. It seems to me that the socket in `hello.xhtml` is application scoped since it is defined as the following:
```xhtml
<f:websocket channel="helloChannel" onmessage="onMessage" />
```
For this use case I understand your suggestion. 

Just for clarification:
In my case the same error appears when I define a session scoped socket. In my use case, the socket needs only be accessible for the current user session and can be destroyed/recreated every time the user logs off/in.

```xhtml
<f:websocket
	id="tasklistSocket"
	channel="tasklistSocket"

	user="#{loginController.getSessionId()}"
	connected="true">
```

Starting the server and deploying the application the first time works well. But if the application is deployed the second time (e.g. a new development build) the following exception is thrown and the socket connection won't be established for the second session. Instead the client tries to establish the socket infinite times (see screenshot):

```
2019-05-24 08:16:16,419 INFO  [org.jboss.as.repository] WFLYDR0001: Content an Speicherort \JBoss\standalone\data\content\de\281c3f7c42e36ea61161619efc1e237cef4570\content hinzugef³gt
2019-05-24 08:16:16,421 INFO  [org.wildfly.extension.undertow] WFLYUT0022: Web-Kontext deregistriert: "/webclient" von Server "default-server"
2019-05-24 08:16:16,426 ERROR [org.jboss.weld.Bean] WELD-000019: Error destroying an instance com.sun.faces.push.WebsocketChannelManager$ViewScope@243d3e43 of Managed Bean [class com.sun.faces.push.WebsocketChannelManager$ViewScope] with qualifiers [@Any @Default]
2019-05-24 08:16:16,426 DEBUG [org.jboss.weld.Bean] Catching: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke protected void com.sun.faces.push.WebsocketChannelManager$ViewScope.deregisterViewScope() on com.sun.faces.push.WebsocketChannelManager$ViewScope@243d3e43
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.preDestroy(DefaultLifecycleCallbackInvoker.java:76)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.injection.producer.BasicInjectionTarget.preDestroy(BasicInjectionTarget.java:127)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.bean.ManagedBean.destroy(ManagedBean.java:192)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.view.ViewScopeContextManager.destroyBeans(ViewScopeContextManager.java:178)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.view.ViewScopeContextManager.sessionDestroyed(ViewScopeContextManager.java:380)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.view.ViewScopeManager.sessionDestroyed(ViewScopeManager.java:369)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.WebappLifecycleListener.sessionDestroyed(WebappLifecycleListener.java:241)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.config.ConfigureListener.sessionDestroyed(ConfigureListener.java:435)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.ApplicationListeners.sessionDestroyed(ApplicationListeners.java:315)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.SessionListenerBridge.doDestroy(SessionListenerBridge.java:98)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.SessionListenerBridge.sessionDestroyed(SessionListenerBridge.java:78)
        at io.undertow.core@2.0.19.Final-redhat-00001//io.undertow.server.session.SessionListeners.sessionDestroyed(SessionListeners.java:61)
        at io.undertow.core@2.0.19.Final-redhat-00001//io.undertow.server.session.InMemorySessionManager.stop(InMemorySessionManager.java:136)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$3.call(DeploymentManagerImpl.java:617)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$3.call(DeploymentManagerImpl.java:607)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@7.2.1.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.1.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.1.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.1.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at io.undertow.servlet@2.0.19.Final-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl.stop(DeploymentManagerImpl.java:621)
        at org.wildfly.extension.undertow@7.2.1.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.stopContext(UndertowDeploymentService.java:135)
        at org.wildfly.extension.undertow@7.2.1.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$2.run(UndertowDeploymentService.java:117)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
        ... 32 more
Caused by: org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.ApplicationScoped
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:123)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
        at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.push.WebsocketSessionManager$Proxy$_$$_WeldClientProxy.deregister(Unknown Source)
        at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.push.WebsocketChannelManager$ViewScope.deregisterViewScope(WebsocketChannelManager.java:213)
        ... 37 more

2019-05-24 08:16:16,429 INFO  [xxx.web.core.controller.LoginController] Calling dispose for [[LoginInformation]
        SessionPrincipal: [WebSessionId: [pwiQKWJDbuim8Yk0dyTmFAQLH2HLaT2KRGiSUprV], shortCut [DBA], employeePk [ged-personpk33#employee18]]
        ]
2019-05-24 08:16:17,051 INFO  [org.jboss.as.server.deployment] WFLYSRV0028: Deployment von webclient.war in (runtime-name: "webclient.war") 631ms gestoppt
2019-05-24 08:16:17,053 INFO  [org.jboss.as.server.deployment] WFLYSRV0027: Starte Deployment von "webclient.war" (runtime-name: "webclient.war")
2019-05-24 08:16:18,976 INFO  [org.jboss.weld.deployer] WFLYWELD0003: Weld-Deployment webclient.war wird verarbeitet
[...]
2019-05-24 08:16:26,033 INFO  [org.jboss.as.server] WFLYSRV0016: Deployment "webclient.war" durch Deployment "webclient.war" ersetzt
2019-05-24 08:16:26,039 INFO  [org.jboss.as.repository] WFLYDR0002: Content an Speicherort \JBoss\standalone\data\content\87\b8badc6e12f8b1a2f7880146236f0d2f421500\content entfernt
2019-05-24 08:16:42,390 INFO  [de.cursor.jevi.web.core.controller.LoginController] Used demo login credentials for [[LoginInformation]        
        WebSessionId: [LX_OnfkzriiaGQ9BC05Rm-0SuUu-ntDDdOCiDirO]]
```

![image](https://user-images.githubusercontent.com/853698/58307132-03c63f80-7dfe-11e9-9306-abcfcfe0c4c0.png)

If you need any further information or assistance, just ping me.

Greetings!

**Comment by BalusC** [comment] 2019-06-11 00:29
> Instead the client tries to establish the socket infinite times (see screenshot):

That part was fixed recently https://github.com/eclipse-ee4j/mojarra/issues/4565

**Comment by bagges** [comment] 2019-07-01 13:09
Is there a workaround for this? I have the same problem on Wildfly 16.

**Comment by pzygielo** [comment] 2019-08-01 18:31
> > Instead the client tries to establish the socket infinite times (see screenshot):
> 
> That part was fixed recently #4565

@BalusC - just to make sure, as it's possible I'm missing something. #4565 closed by #4566 seems to be merged only to EE4J branch, and not to 2.3 nor master. Is that as intended?

**Comment by stephan-wenders** [comment] 2020-01-14 15:01
> 
> 
> > Instead the client tries to establish the socket infinite times (see screenshot):
> 
> That part was fixed recently #4565

Sorry, hoped that this problem was fixed in the last 6 month.
I am trying to migrate from primefaces 6.x to primefaces 7.x.
Since we are using websockets with primepush i have to migrate to jsf 2.3 to use the new websocket feature.
We are currently using wildfly 18.0.1.final (Mojarra 2.3.9.SP04) but i still have the same problem as described above. Everything works fine until redeployment, then the client tries to establish the socket infinite times.
Perhaps i missed something, for me the scope attributes tells me something about who delivers the message.

> The scope of the websocket channel. It may not be an EL expression and allowed values are application, session and view, case insensitive. When the value is application, then all channels with the same name throughout the application will receive the same push message. When the value is session, then only the channels with the same name in the current user session will receive the same push message. When the value is view, then only the channel in the current view will receive the push message. The default scope is application. When the user attribute is specified, then the default scope is session

Any help or new information is appreciated

**Comment by rsisto** [comment] 2020-12-13 17:00
Hi!
I'm just testing this out in Wildfly 21.
Same problem. It's just a test websocket, from a pluralsight course on java ee8 update course.
From a fresh wildfly start, everything works out. If I redeploy the application, I see infinite websocket equests from the client as noted by @DennisBayer .

Here's the project zip, in case anyone wants to try it out. 
The test is with websocket.xhtml (where the problem is seen), and websocketSend.xhtml (this sends a message to the websocket clients) 
[javaee8test.zip](https://github.com/eclipse-ee4j/mojarra/files/5684996/javaee8test.zip)

I also appreciate news on this.

**Comment by erickdeoliveiraleal** [comment] 2020-12-13 21:33
Could it be related to this open pulm request? https://github.com/eclipse-ee4j/mojarra/pull/4803

**Comment by NoelVaes** [comment] 2021-04-16 06:54
I encounter the same problems. Any progress on this issue?

**Comment by BalusC** [comment] 2021-04-19 11:24
There are 2 separate problems mentioned in this ticket:

1. Websocket not working after application redeploy (because session persistence wasn't enabled in server)
2. Websocket trying to reconnect infinitely instead of finitely (because of browser specific bug)

Which one exactly are you referring to?

1. Solution: enable session persistence in server
2. Solution: upgrade to at least Mojarra 2.3.15 (unfortunately still not released at time of writing)

Closing off. The fix for problem 2 was indeed done long time ago but unfortunately slipped through actual release because of an opaque oracle-eclipse migration process. So it was re-done in https://github.com/eclipse-ee4j/mojarra/issues/4802

**Closed by BalusC** 2021-04-19 11:24 UTC

**Comment by Toru47** [comment] 2021-05-17 14:01
Is there a workaround for "Websocket trying to reconnect infinitely instead of finitely"?

**Comment by stephan-wenders** [comment] 2021-05-18 05:43
Hi!

sorry for addressing this problem again. i'am using wildfly 18 and everything works fine using omnifaces sockets. I neither changed the server configuration nore the browser. I do not understand the given explanation, but hope one of the next wildfly releases is shipped with a Mojarra version including those fixes.

Geetings from Duisburg
Stephan
