### ISSUE TITLE
WildFly includes Mojarra 4.0.6 and is seeing 16 (old) Faces 4.0 TCK failures

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/mojarra#5436] opened 2024-04-09 16:14 UTC
**Describe the bug**

I'm not sure of the cause yet.  With https://www.eclipse.org/downloads/download.php?file=/jakartaee/faces/4.0/jakarta-faces-tck-4.0.3.zip + latest [WildFly](https://github.com/wildfly/wildfly/) changes that includes Mojarra 4.0.6 we are seeing the following TCK tests failing:
> [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/application/navigationcase/URLClient.java#navigationCaseGetBookmarkableURLTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/application/navigationcase/URLClient.java#navigationCaseGetRedirectURLTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentEncodeBeginELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentEncodeEndELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentGetCurrentComponentNullTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentGetCurrentComponentTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentGetCurrentCompositeComponentNullTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentPopComponentFromELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/html/htmlform/URLClient.java#uiComponentPushComponentToELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentEncodeBeginELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentEncodeEndELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentGetCurrentComponentNullTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentGetCurrentComponentTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentGetCurrentCompositeComponentNullTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentPopComponentFromELTest
[javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/component/uiform/URLClient.java#uiComponentPushComponentToELTest

The WildFly tracking issue is https://issues.redhat.com/browse/WFLY-19220

**To Reproduce**

I have reproduced it locally with WildFly but GlassFish is still using Mojarra 4.0.5 so didn't try that.

**Comment by scottmarlow** [comment] 2024-04-09 16:26
Do any of the changes in https://github.com/eclipse-ee4j/mojarra/compare/4.0.5-RELEASE...4.0.6-RELEASE change anything that could cause failures like shown in [https://issues.redhat.com/browse/WFLY-19220](https://issues.redhat.com/browse/WFLY-19220?focusedId=24505460&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24505460)

**Comment by scottmarlow** [comment] 2024-04-09 17:49
I'm doing a `git bisect` and testing with different changes included in the `4.0.6` release to narrow the cause down.

**Comment by scottmarlow** [comment] 2024-04-09 18:22
`git bisect` identified https://github.com/eclipse-ee4j/mojarra/commit/5a23e8a4 as the cause.

**Comment by pizzi80** [comment] 2024-04-10 11:02
If the stacktrace is the one pasted in the textarea on the redhat website you linked

what I see is:

```
[javatest.batch] Caused by: java.util.NoSuchElementException: No value present
[javatest.batch] 	at java.base/java.util.Optional.get(Optional.java:148)
[javatest.batch] 	at jakarta.faces.impl@4.0.6//com.sun.faces.util.Util.getResponseEncoding(Util.java:1680)
[javatest.batch] 	at jakarta.faces.impl@4.0.6//com.sun.faces.util.Util.getResponseEncoding(Util.java:1629)
[javatest.batch] 	at jakarta.faces.impl@4.0.6//com.sun.faces.context.ExternalContextImpl.encodeBookmarkableURL(ExternalContextImpl.java:976)
[javatest.batch] 	at jakarta.faces.impl@4.0.6//com.sun.faces.application.view.MultiViewHandler.getBookmarkableURL(MultiViewHandler.java:327)

```

if this is the error, the cause is a bug inside the `Util` class:

```
public static String getResponseEncoding(FacesContext context) {
   return getResponseEncoding(context, Optional.empty());
}
```

and it's caused by the `Omptional.empty()` passed as a second parameter which 
throws a `NoSuchElementException` if the value is `null` , 
which is the exact value of `Omptional.empty()` :)

**Comment by pizzi80** [comment] 2024-04-10 11:05
probably it's better to pass a `String` and not an `Optional<String>`
and I would pass the constant `RIConstants.CHAR_ENCODING`

**Comment by soul2zimate** [comment] 2024-04-10 11:21
Hi @scottmarlow , @TomasHofman actually opened an issue https://github.com/eclipse-ee4j/mojarra/issues/5429 for very similar stacktrace, but he identified different commit causes the failure.

**Comment by BalusC** [comment] 2024-04-10 12:58
Please retry with 4.0.7-SNAPSHOT. This has only been fixed in 4.0.7 for #5429.

Or let me know if we should release 4.0.7 as soon as possible.

**Comment by scottmarlow** [comment] 2024-04-10 13:04
> Please retry with 4.0.7-SNAPSHOT. This has only been fixed in current 4.0 branch for https://github.com/eclipse-ee4j/mojarra/issues/5429.
>
>Or let me know if we should release 4.0.7 as soon as possible.

@BalusC thanks, I will test with ^

**Comment by scottmarlow** [comment] 2024-04-10 17:05
> Please retry with 4.0.7-SNAPSHOT. This has only been fixed in current 4.0 branch for #5429.
> 
> Or let me know if we should release 4.0.7 as soon as possible.

@BalusC thanks again for the quick fix!  WildFly just passed all of the Faces (old + new) TCK tests with 4.0.7-SNAPSHOT! 

We will switch to the 4.0.7 release when available.  Having the 4.0.7 release as soon as possible would be appreciated! :-)

**Comment by BalusC** [comment] 2024-04-10 18:13
Okay I'll look what I can do.

**Comment by BalusC** [comment] 2024-04-11 09:46
Mojarra 4.0.7 will be released today.

**Comment by BalusC** [comment] 2024-04-11 09:46
This issue is technically speaking duplicate of https://github.com/eclipse-ee4j/mojarra/issues/5429

**Closed by BalusC** 2024-04-11 09:46 UTC
