### ISSUE TITLE
TCK Signature tests fail due to generics based API changes and deprecated annotations

### ISSUE THREAD

**Issue by anajosep** [eclipse-ee4j/mojarra#4523] opened 2018-12-07 03:46 UTC
The Java EE 8 signature tests failed for the following JSF packages.
		javax.faces.webapp(static mode)
		javax.faces.webapp(reflection mode)

The failures seems to be caused due to the following type of changes in the jakarta.faces-api.jar which was integrated to Eclipse GlassFish 5.1.0.
- Some methods uses generics in their signature (compared to Java EE 8 api)
- Some annotations were deprecated. (compared to Java EE 8 api)

Missing Methods
---------------

javax.faces.webapp.AttributeTag:        method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class)
javax.faces.webapp.ConverterELTag:      method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class)
javax.faces.webapp.ConverterTag:        method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class)
javax.faces.webapp.FacetTag:            method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class)
javax.faces.webapp.ValidatorELTag:      method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class)
javax.faces.webapp.ValidatorTag:        method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class)

Added Methods
-------------

javax.faces.webapp.AttributeTag:        method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class<?>)
javax.faces.webapp.ConverterELTag:      method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class<?>)
javax.faces.webapp.ConverterTag:        method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class<?>)
javax.faces.webapp.FacesServlet:        method public final void javax.faces.webapp.FacesServlet.initializeAllowedKnownHttpMethods(java.util.List<java.lang.String>)
javax.faces.webapp.FacetTag:            method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class<?>)
javax.faces.webapp.ValidatorELTag:      method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class<?>)
javax.faces.webapp.ValidatorTag:        method public final static javax.servlet.jsp.tagext.Tag javax.servlet.jsp.tagext.TagSupport.findAncestorWithClass(javax.servlet.jsp.tagext.Tag,java.lang.Class<?>)

Added Annotations
-----------------

javax.faces.webapp.UIComponentClassicTagBase:               EVAL_BODY_TAG:anno 0 java.lang.Deprecated()
javax.faces.webapp.UIComponentELTag:    EVAL_BODY_TAG:anno 0 java.lang.Deprecated()
javax.faces.webapp.UIComponentTag:      EVAL_BODY_TAG:anno 0 java.lang.Deprecated()
--- affected javax.faces.webapp.UIComponentBodyTag

These changes should be reverted, so that Eclipse GlassFish 5.1.0 passes the Java EE CTS 8.0.

**Comment by ggam** [comment] 2018-12-08 11:57
From what I see, these problems are caused by changes on the extended JSP classes.  https://github.com/eclipse-ee4j/jsp-api/pull/85 should fix this issue.

**Comment by arjantijms** [comment] 2018-12-08 14:14
@ggam thanks again. I merged the PR, but re-staging failed on the parent pom not having been updated to 1.0.5 and the servlet dependency still being javax instead of Jakarta.

@anajosep can you review the new PR? https://github.com/eclipse-ee4j/jsp-api/pull/86

**Comment by anajosep** [comment] 2018-12-11 12:32
@arjantijms When would this restaged JSP be integrated to Eclipse GlassFish. I have jobs to run Standalone TCK only against GlassFish bundle.

**Comment by arjantijms** [comment] 2018-12-11 13:13
@anajosep there's no explicit re-integration needed. Just a clean build of Eclipse GlassFish again (with an empty .m2).

**Comment by m0mus** [comment] 2019-01-07 10:50
Last CTS run doesn't have these errors. Closing the bug.

**Closed by m0mus** 2019-01-07 10:50 UTC
Labels: GlassFish 5.1, bug
