### ISSUE TITLE
Error prone JSF implementation causes broken AJAX communication

### ISSUE THREAD

**Issue by abelet** [eclipse-ee4j/mojarra#4488] opened 2018-10-05 13:15 UTC
## Maven project demonstrating the problem ##
[jsf-ajax-failure.zip](https://github.com/eclipse-ee4j/mojarra/files/2450650/jsf-ajax-failure.zip)

I mentioned problems connected to primefaces below, but the issue is about the way how JSF makes from a small mistake an unrecoverable error.

## Description of the implementation that causes trouble ##

The com.sun.faces.renderkit.html_basic.HtmlResponseWriter provides a functionality for renaming HTML tag names generated by JSF Components. With this implementation the following JSF code:

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:ui="http://java.sun.com/jsf/facelets"
   xmlns:pass="http://xmlns.jcp.org/jsf/passthrough"
>
      <h:outputLabel value="Welcome" pass:label_text="Welcome" pass:elementName="span"/>
</ui:composition>
```
will produce a HTML like this:

```html
<span label_text="Welcome">Welcome</span>
```

The key elements of the implementation are the following member variable and methods of the HtmlResponseWriter class:

```java
private LinkedList<String> elementNames;
public void startElement(String name, UIComponent componentForElement)
public void endElement(String name)
private String pushElementName(String original)
private String popElementName(String original)
private String getElementName(String name)
```
In general every JSF component has a renderer class with two major methods:

```java
public void encodeBegin(FacesContext context, UIComponent component)
public void encodeEnd(FacesContext context, UIComponent component)
```

In case of the outputLabel component the com.sun.faces.renderkit.html_basic.LabelRenderer class is the renderer class.
To put it simply encodeBegin method will call the startElement for creating the opening HTML tag, and the encodeEnd method calls the endElement to create the closing HTML tag. The LabelRenderer class provides the “label” element name parameter in the startElement call. But the startElement method will override this element name by calling the pushElementName method. The pushElementName will not provide the name itself, instead it calls the getElementName method for this. The getElementName will check if a pass-through attribute named elementName was provided. If so, it will return the value of this attribute instead of the original element name provided by the component’s renderer class. The pushElementName method will examine the original and the returned name. If they differ, the new one will be pushed into the elementNames stack, and this will be the one to be returned and written out. 
When a JSF component’s renderer class finally calls the endElement for the closing the tag it will call the popElementName passing the element name parameter along. If the elementNames field is null or empty, then the passed element name will be written out. Otherwise the last element which was pushed into the elementNames  stack will be returned and written out.

### Problem with the implementation ###

JSF components are not perfect. Their implementations can have some faults. For example the primefaces PanelGrid component is liable for not closing table rows. It does not close the last row if “actual number of columns” cannot be divided by the “value of columns attribute” without a remainder.   For example the following JSF fragment:

```html
<p:panelGrid columns="2" >
    <h:outputLabel value="x"/>
    <h:outputLabel value="x"/>
    <h:outputLabel value="x"/>
</p:panelGrid>
```
produces a HTML table missing a closing TR tag:

```xml
<table id="form:j_idt5" class="ui-panelgrid ui-widget" role="grid">
    <tbody>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
        </tr>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
    </tbody>
</table> 
```
The JSF fragment cannot be blamed for the problem. It is a natural need to have 2 components in the first and 1 in the second row. So the PanelGrid implementation is wrong, but the improper HTML will be rendered perfectly by the browser. Unfortunately the JSF implementation can make from this mistake an unrecoverable error. But before describing how and in in which circumstances it is done, I have to mention another important change in the JSF implementation which made 2.3 version far more risky to use than 2.2. In JSF 2.2.13 the pushElementName method had the following code fragment:

```java
if (original.equals("option")) {
    return original;
}
```
Which has been changed in JSF 2.3 to this:

```java
if (original.equals("option")) {
     if(elementNames == null) {
        elementNames = new LinkedList<>();
     }
     elementNames.push(original);
     return original;
}
```

The risk existed in JSF 2.2 implementation, but with the changes above made JSF 2.3 dangerous, and the problem urgent to be solved. Shortly everyone would like to move towards JSF 2.3, but meanwhile everyone needs a reliable application. Overriding the HTML tag name which is generated by a JSF component is a rare situation, but most applications use a selectOneMenu which will have options.  

That’s everything. If you use a selectOneMenu, a not so well written component, and use JSF 2.3 your AJAX communication is likely to fail. Let’s make an example. We’ll have a main page with two links which will refresh parts of the page. When you click on a link two regions (selectOnePanel and panelGridPanel) will be refreshed / updated. For example:

```xml
<h:body>
  <h:form id="form">
    <p:commandLink update="selectOnePanel panelGridPanel" action="#{ajaxTestTabMB.doTabChange(0)}">
      <h:outputText value="/dummyPage.xhtml" />
    </p:commandLink>
    <p:commandLink update="selectOnePanel panelGridPanel" action="#{ajaxTestTabMB.doTabChange(1)}">
      <h:outputText value="/errorCaseSelectOne.xhtml" />
    </p:commandLink>
    <h:panelGroup id="selectOnePanel">
      <ui:include src="#{ajaxTestTabMB.firstPage}"/>
    </h:panelGroup>
    <h:panelGroup id="panelGridPanel">
      <ui:include src="#{ajaxTestTabMB.secondPage}"/>
    </h:panelGroup>
  </h:form>
</h:body>
```

We have 4 subpages, but I describe just 2, which are causing the trouble. So we have the errorCaseSelectOne.xhtml, which will be displayed in selectOnePanel

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:ui="http://java.sun.com/jsf/facelets"
>
      <p:selectOneMenu>
          <f:selectItem itemLabel="100"/>
      </p:selectOneMenu>
</ui:composition>
```
and the errorCasePanelGrid.xhtml which will be displayed in panelGridPanel

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
 xmlns:ui="http://java.sun.com/jsf/facelets"
 xmlns:p="http://primefaces.org/ui"
 xmlns:h="http://java.sun.com/jsf/html">

      <p:panelGrid columns="2" >
       <h:outputLabel value="x"/>
       <h:outputLabel value="x"/>
       <h:outputLabel value="x"/>
      </p:panelGrid>

</ui:composition>
```

When you click on the second link,  which calls doTabChange(1), an AJAX request will be sent to the server, and on the server side an AJAX response will be created. If the errorCasePanelGrid.xhtml specified 3 (instead of 2) for the columns attribute above, we would get:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
          <changes>
                   <update id="javax.faces.Resource">
                             <![CDATA[<link type="text/css" rel="stylesheet" href="/jsf-test-app/javax.faces.resource/components.css.xhtml?ln=primefaces&amp;v=6.2" />]]>
                   </update>
                   <update id="form:selectOnePanel">
                             <![CDATA[<span id="form:selectOnePanel"><div id="form:j_idt19" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" role="combobox" aria-haspopup="true" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="form:j_idt19_focus" name="form:j_idt19_focus" type="text" autocomplete="off" aria-expanded="false" /></div><div class="ui-helper-hidden-accessible"><select id="form:j_idt19_input" name="form:j_idt19_input" tabindex="-1" aria-hidden="true"><option value="" selected="selected" data-escape="true">100</option></select></div><label id="form:j_idt19_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="form:j_idt19_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="form:j_idt19_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="100" tabindex="-1" role="option">100</li></ul></div></div></div><script id="form:j_idt19_s" type="text/javascript">PrimeFaces.cw("SelectOneMenu","widget_form_j_idt19",{id:"form:j_idt19"});</script></span>]]>
                   </update>
                   <update id="form:panelGridPanel">
                             <![CDATA[<span id="form:panelGridPanel"><table id="form:j_idt20" class="ui-panelgrid ui-widget" role="grid"><tbody><tr class="ui-widget-content" role="row"><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td></tr></tbody></table></span>]]>
                   </update>
                   <update id="j_id1:javax.faces.ViewState:0">
                             <![CDATA[-6160204276543946460:5353968715620084221]]>
                   </update>
          </changes>
</partial-response> 
```

But we specified 2, and the response will be:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
          <changes>
                   <update id="javax.faces.Resource">
                             <![CDATA[<link type="text/css" rel="stylesheet" href="/jsf-test-app/javax.faces.resource/components.css.xhtml?ln=primefaces&amp;v=6.2.9" />]]>
                   </update>
                   <update id="form:selectOnePanel"><![CDATA[<span id="form:selectOnePanel"><div id="form:j_idt19" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" role="combobox" aria-haspopup="true" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="form:j_idt19_focus" name="form:j_idt19_focus" type="text" autocomplete="off" aria-expanded="false" /></div><div class="ui-helper-hidden-accessible"><select id="form:j_idt19_input" name="form:j_idt19_input" tabindex="-1" aria-hidden="true"><option value="" selected="selected" data-escape="true">100</option></select></div><label id="form:j_idt19_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="form:j_idt19_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="form:j_idt19_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="100" tabindex="-1" role="option">100</li></ul></div></div></div><script id="form:j_idt19_s" type="text/javascript">PrimeFaces.cw("SelectOneMenu","widget_form_j_idt19",{id:"form:j_idt19"});</script></span>]]>
                   </update>
                   <update id="form:panelGridPanel">
                             <![CDATA[<span id="form:panelGridPanel"><table id="form:j_idt20" class="ui-panelgrid ui-widget" role="grid"><tbody><tr class="ui-widget-content" role="row"><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td></tr><tr class="ui-widget-content" role="row"><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td></tr></tbody></table>]]>
                   </span>
                   <update id="j_id1:javax.faces.ViewState:0"><![CDATA[-3598172727742462547:-7062186675995454000]]>
                   </update>
          </update>
</partial-response>
```
You probably remember the problem with the PanelGrid component’s renderer, where the following is generated:

```html
<table id="form:j_idt5" class="ui-panelgrid ui-widget" role="grid">
    <tbody>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
        </tr>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
    </tbody>
</table> 
```

But in the AJAX response the last row is closed. Why? Because we have a selectOnePanel with an option in the AJAX answer. While writing out the option HTML tag in the HtmlResponseWriter class, the elementNames stack will be initiated. Once the elementNames stack become initiated, every single HTML tag opening will be pushed into it. In other words, writing out the option HTLM tag changes everything. When a component renderer calls the HtmlResponseWriter.endElement (in the encodeEnd method), the value of the name parameters doesn’t matter any more. The closing HTML tag will be read from the elementNames  stack. So when the PanelGridRenderer want to close the tbody element, it will close the tr element. Every time a renderer does not close an element which was opened, an extra element remains in the stack, which will cause unexpected closing tag names. The extra element is responsible for the invalid AJAX response above. For example before the partial-response tag an update tag has been placed instead of the changes tag. This is how the JSF 2.3 implementation made from a syntax error which can be handled by the browser and invalid AJAX response, and our application went wrong.

### Trying to understand  the changes in JSF and finding a solution ###

Before the idea for tag renaming emerged the relevant elements of the implementation were the following of the HtmlResponseWriter class:

```java
public void startElement(String name, UIComponent componentForElement)
public void endElement(String name)
```

Because the endElement method does not receive the componentForElement parameter, there is no way to read the elementName pass-through attribute. To solve this I can think of two solutions. One of them was implemented by adding these new elements to the implementation: 

```java
private LinkedList<String> elementNames;
private String pushElementName(String original)
private String popElementName(String original)
private String getElementName(String name)
```
Another solution might have been to change the signature of the endElement method. This kind of change means that JSF is not backward compatible and every JSF component renderer has to be modified when switching to this new JSF version.
A third option might have been not to implement a possibility for HTML tag renaming at all. If I could go back in time, and anyone would ask me, maybe I would choose this, because for me a predictable and reliable implementation is far more important than overriding the preferred HTML tag name by the component renderer.

**Comment by abelet** [comment] 2018-10-05 13:17
I mentioned problems connected to primefaces but the issue is about the way how JSF makes from a small mistake an unrecoverable error.

**Comment by manfredriem** [comment] 2018-10-06 19:30
@abelet While I understand the predicament you are in, it is not the responsibility of the JSF runtime to fix incorrect usage of the ResponseWriter API. If any component produces incorrect HTML by virtue of not calling the ResponseWriter correctly, the component needs to be fixed. Closing this as works as designed.

**Closed by manfredriem** 2018-10-06 19:30 UTC

**Comment by abelet** [comment] 2018-10-06 22:31
I can easily fix the primefaces component, but cannot trust and use JSF  any more, if you leave it as it is.

**Comment by abelet** [comment] 2018-10-07 21:45
I can easily fix the primefaces component.
My major concern is how fault tolerant the JSF runtime is. The current JSF runtime hides the real problem, and makes from an invalid HTML a valid one, and produces an invalid partial response. It is really hard to find an error which was hidden by the JSF runtime.
The JSF runtime is also expected not to make things worse, errors more severe. In this case an incorrect HTML leads to an incorrect partial response, and this is the responsibility of the JSF runtime, which should not be shifted onto JSF frameworks like primefaces.

**Comment by arjantijms** [comment] 2018-10-07 22:07
@abelet There's some attempt by the ResponseWriter to attempt to fix thing at some level if I'm not mistaken. Just failing fast might have been a lot better there.

It's a bit like the old HTML parsing, that was very forgiving since it was thought that page authors would not like and/or understand errors. But the effect was only that different browsers tried to fix invalid things differently, which led to the entire miss of IE HTML.

Although JSF 3.0 is a breaking release, breaking potentially even more by now throwing an error right away instead that old attempt to fix isn't a decision to take lightly either. I could however see us deprecating the old "fixing" behaviour in 3.0, maybe with a switch to throw an error instead, and then making the error the default in 3.1.

(also note that I haven't studied the problem in depth, so I'm replying from the top of my head)

**Comment by abelet** [comment] 2018-10-08 09:18
I tried the error throwing approach before posting the issue. Unfortunately for me it did not seem any better than the current one. I got a stack trace, but seeing this, I thought from that I would never get any idea what caused the trouble. I think the only right way to handle things, to leave the wrong HTML as it were. This is the way, how JSF 2.2 worked (in almost every situation). If the browser can’t handle an invalid HTML response, we can deal with it. We will see the wrong response, and from that we will know which component caused it. We will also see which part of the page is wrong. We will have a lot of information about the problem.

Now with JSF 2.3 this days are gone.  JSF 2.3 will hide the real problem, making error detection a nightmare. I cannot describe how much time I spent finding out what component is wrong. We would like to switch to wildfly 14 now, but the JSF 2.3 makes it an irresponsible decision. To be more accurate JSF 2.2 already had the problem, but it was unlikely to cause trouble. I won’t write about the details because they are in the original post.

**Comment by erickdeoliveiraleal** [comment] 2018-10-08 23:18
This is a high priority bug, many systems may break if they use the Mojarra 2.3 implementation in production. This happened to me, so I went back to using 2.2

**Comment by abelet** [comment] 2018-10-08 23:30
@erickdeoliveiraleal 's bug can be found here: https://github.com/jboss/mojarra/issues/21

**Comment by erickdeoliveiraleal** [comment] 2018-10-24 14:32
Should not this issue be reopened?

**Comment by arjantijms** [comment] 2018-10-24 14:38
@erickdeoliveiraleal It can indeed always be re-opened if needed. Might be a good idea to wait a little what the JBoss people have to say about this, and then port their fix (if any) to upstream Mojarra.

**Comment by SirError** [comment] 2019-03-28 11:26
Is there any news about this issue? 
I'm trying to migrate a project from wildfly 10 (jsf 2.2) to wildfly 16 (jsf 2.3.8) and facing the same problems.
If I disable the wildfly jsf and use the version 2.3.2 I don't have any problem.
