### ISSUE TITLE
Vanish input data after triggering an immediate command

### ISSUE THREAD

**Issue by he-bio** [eclipse-ee4j/mojarra#5073] opened 2022-03-28 14:27 UTC
**Describe the bug**

With JSF 2.3.17 an immediate command let vanish all input data of a "form" which has no bindings. This happened only with: PARTIAL_STATE_SAVING == false

With JSF 2.3.15 this is not the case, all data will be displayed after triggering an immediate command.

Is this a bug or expected behavior when PARTIAL_STATE_SAVING == false?

**To Reproduce**

1. see attached test project which was created under the mojarra servlet40 tests package: [mojarra-2.3.17-immediateCommand-test.zip](https://github.com/eclipse-ee4j/mojarra/files/8363627/mojarra-2.3.17-immediateCommand-test.zip)
2. tested on Glassfish 5.0 with JSF 2.3.17 and 2.3.15

**Expected behavior**

After triggering an immediate command all input data of a "form" are still visible. The render response phase don't let the data vanish.

**Screenshots**

![broken](https://user-images.githubusercontent.com/102530961/160419074-c5dbf7a3-5571-4872-91e2-17b02ffb452e.png)

![correct](https://user-images.githubusercontent.com/102530961/160419079-bbd974be-7b6d-4a15-aa49-76233391d63e.png)

**Comment by miguelzapaton** [comment] 2022-03-30 09:49
+1 

2.3.17 breaks my application. The state of all form fields is lost when validation fails.

2.3.16 still works perfectly.

**Comment by BalusC** [comment] 2022-04-06 09:11
> With JSF 2.3.17 an immediate command let vanish all input data of a "form" which has no bindings

Reproduced.

> 2.3.17 breaks my application. The state of all form fields is lost when validation fails.

Norepro. Probably you also had an immediate command and it's not related to validation failures.

---

It's really bad that this has slipped through the integration tests. Historically they also ran with PSS turned off but this is since Jakarta migration not anymore happening.

That said, the immediate attribute has since JSF 2.0 lost its real value because the originally intended functionality can be achieved in a much more robust way using <f:ajax> or <h:button>. The immediate attribute should preferably NOT be used in JSF 2.0+ applications. See also https://stackoverflow.com/questions/13071512/why-was-immediate-attribute-added-to-the-editablevalueholders

Nonetheless this bug indeed really warrants analysis and fixing.

**Comment by BalusC** [comment] 2022-04-06 10:56
Regression of performance optimizations done in https://github.com/eclipse-ee4j/mojarra/pull/4808. It was in hindsight not compatible with Full State Saving. It was not immediately obvious how to get it to work with FSS anyway, so I've for now simply restored the original implementation and added an if/else on PSS/FSS and let the FSS condition run the original implementation.

Noted should be that there were and are plans to deprecate and remove FSS in a future Faces version simply because PSS is far superior over it.

**Comment by arjantijms** [comment] 2022-04-06 11:58
> Noted should be that there were and are plans to deprecate and remove FSS in a future Faces version simply because PSS is far superior over it.

Indeed, FSS will be deprecated in Faces 4 for removal. (small historical note, it should never have been included in the first place, and during the initial JSF design plans it was already controversial to fully save the state)

**Comment by BalusC** [comment] 2022-04-10 14:49
> We haven't discussed it yet afaik, but maybe we should consider deprecating the immediate attribute as well?

Definitely in favor of this.

**Comment by BalusC** [comment] 2022-04-10 15:02
Upmerged into 3.x and 4.x branches.

> Is there a SNAPSHOT or NIGHTLY repo for the 2.3 branch?

Frankly I'm not sure where it is. It was previously automated via Hudson. @arjantijms how exactly is this currently configured?

**Comment by comiCH** [comment] 2022-04-22 13:02
Hello there

We are currently experiencing some problems with Mojarra 2.3.17 which might be related to this issue and #5065.
These problems seem to have their root cause in the changes of #4808.

We are migrating an app with JSF and PrimeFaces 8 to WildFly 26.0.1.
Doing so, we found out that several PrimeFaces components no longer function properly, e.g.
- the AutoComplete component never shows any suggestions
- filtering a DataTable does not do anything
- paging of a DataTable does work properly (selecting a row on a page > 1 jumps the table back to page 1)

We dug deep into this and found out, that the problem is related to the changes of the _ComponentStateHelper.put(Serializable key, String mapKey, Object value)_ method made with #4808.
Using the AutoComplete malfunction as a starting point, we made the same observations as @OBreidenbach documented in #5065.
In RESTORE_VIEW a new AutoComplete instance gets created.
In APPLY_REQUEST_VALUES this AutoComplete instance gets populated with proper suggestions.
In RENDER_RESPONSE the previously created and populated AutoComplete is not found by _ComponentSupport.findChildByTagId(...)_ and a new AutoComplete instance (with empty suggestions) is created and rendered instead.

We found out that the reason for _ComponentSupport.findChildByTagId(...)_ to not find the previously created and populated AutoComplete component lies in the method _ComponentStateHelper.put(Serializable key, String mapKey, Object value)_.

In this method an attempt to update the _DescendantMarkIdCache_ is made.
But unfortunately this attempt comes too early in this method.
It will simply result in doing nothing since the MARK_ID is not yet available on the component.
The component's MARK_ID will only be available at the very end of the _put_-method.

So we moved the code to update the _DescendantMarkIdCache_ to the end of the _put_-method
and voila, the mentioned problems were gone.

Enclosed you will find the patch of the change we've made.
We think that the patch is reasonable but clearly you can judge our attempt more thoroughly.

[Fixed_too_early_update_of_DescendantMarkIdCache.patch.txt](https://github.com/eclipse-ee4j/mojarra/files/8541172/Fixed_too_early_update_of_DescendantMarkIdCache.patch.txt)

**Comment by BalusC** [comment] 2022-11-16 20:31
Fix has been released in Mojarra 2.3.18 / 3.0.2 / 4.0.0

**Closed by BalusC** 2022-11-16 20:31 UTC
