### ISSUE TITLE
Injection in @FacesValidator

### ISSUE THREAD

**Issue by chris21k** [eclipse-ee4j/mojarra#5119] opened 2022-06-19 00:57 UTC
With Mojarra 4.0.0 and Weld 5.0.0.SP2 injection in a @FacesValidator now works as desired with an annotation @FacesValidator{managed = true), instead of the previously necessary @FacesValidator(value = xxxValidator, managed = true). I believe this was the fix for issue #5075 . So far, so good/great.

However, as long time ago stated in #4245, more precisely in https://github.com/eclipse-ee4j/mojarra/issues/4245#issuecomment-382262305 , it is still necessary to use bean-discovery-mode="all" in beans.xml instead of bean-discovery-mode="annotated". The latter is even default now, for a good reason. However, the bug that injected values in a managed FacesValidator then are null is now even more misleading.  Probably related #5110.

I hope fixing this bug closes the injection in validator odyssey.

Many thanks @BalusC and at all other involved people for the fix of #5075 and for looking into this remaining issue. Thank you all for Jakarta Faces and Mojarra in the great new version 4!

Chris

**Comment by pizzi80** [comment] 2022-06-20 20:30
> However, as long time ago stated in #4245, more precisely in [#4245 (comment)](https://github.com/eclipse-ee4j/mojarra/issues/4245#issuecomment-382262305) , it is still necessary to use bean-discovery-mode="all" in beans.xml instead of bean-discovery-mode="annotated". The latter is even default now, for a good reason. However, the bug that injected values in a managed FacesValidator then are null is now even more misleading. Probably related #5110.

now I understand why for me `@Inject` never worked!!

**Comment by BalusC** [comment] 2022-06-25 14:13
Work around: put a CDI scope annotation on the validator, e.g. `@Dependent` or `@ApplicationScoped`, depending on the desired scope of the state of the validator instance.

**Comment by mnriem** [comment] 2023-09-15 21:38
@chris21k This is by design. 

Note that CDI determines what happens when you use the 'bean-discovery-mode'. 

See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#default_bean_discovery

Closing this as works as designed

**Closed by mnriem** 2023-09-15 21:38 UTC
Labels: 4.0

**Comment by pizzi80** [comment] 2023-09-18 11:11
So 
basically for Faces 4+ the "managed" attribute of `@FacesValidator` 
it's useless and confusing and probably should be removed 

The best way for Faces 5? it's to obtain a Faces Validator only with CDI.

In this way we achieve the following results:
1) remove a useless attribute
2) optimize the validators lifecycle
3) reduce the code inside Faces
4) optimize the memory usage

**Comment by chris21k** [comment] 2026-03-31 13:36
Is there any progress/activity with the "useless" managed attribute in Faces 5, as we already need to provide @DependentScope? As pizzi80 writes, it is rather confusing.

**Comment by BalusC** [comment] 2026-03-31 13:42
Yup, see jakartaee/faces#1584 which I coincidentally worked on 2 days ago: https://github.com/jakartaee/faces/pull/2131/changes#diff-54e572599fd01df13fde235f9293a710809aa052868efb36b2ad4ba4d074c011R88-R96
