### ISSUE TITLE
ArrayIndexOutOfBoundsException with index -2 in HtmlResponseWriter.writeUnescapedCData(...)

### ISSUE THREAD

**Issue by mcbros** [eclipse-ee4j/mojarra#4650] opened 2019-10-25 09:13 UTC
Placing an EL expression that returns an empty String in a script element (and most certainly anywhere as CDATA) leads to an ArrayIndexOutOfBoundsException with index -2 in
HtmlResponseWriter.writeUnescapedCData(...).
The case of an empty String is simply uncovered in the method.

**Comment by der-ambi** [comment] 2019-10-28 12:12
Looks like a regression introduced with commit 0bf29e59bcbba7174c9694f9c2b60e9d8576b3e5 that added writeUnescapedCData() but missed to add the check for an empty buffer.

**Comment by OBreidenbach** [comment] 2019-11-06 13:15
Just got the same failure. So may be the PR can speed up the fixing.

**Comment by OBreidenbach** [comment] 2019-11-06 14:28
Just stumbled across https://github.com/eclipse-ee4j/mojarra/blob/553da11c696a0026bd6d05a5977f89107f6b947e/impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java#L553 
and wondering what would be the correct statement.

**Comment by rmartinc** [comment] 2019-11-07 16:55
Hi,
We are also interested in this issue, but @OBreidenbach your PR seems to be not OK (files changed 726). I see that your commit is just two files. Have you merged the correct master branch? 
Thanks a lot for your effort!

**Comment by OBreidenbach** [comment] 2019-11-08 08:28
Hi,
@rmartinc thanks for your hint. Indeed I did use the last release branch. My first goal was to create a patched Mojarra for my application. But I should not push that as PR.
I hope the new PR is better.

**Comment by rmartinc** [comment] 2019-11-08 08:49
Thanks @OBreidenbach! At least now I see it OK, let's see what the maintainers think about it.

**Comment by jthalmai** [comment] 2019-11-15 14:44
Duplicate of #4647

**Comment by cmunier** [comment] 2020-01-21 08:17
From my perspective, this is a **severe problem** that should be handled with **high priority**.

We are using a component framework where it is common that composite component attributes are used as parameters for encapsulated JavaScript for added functionality. It is a common case that the default value of an optional attribute is empty. So there you now always end up with an Exception. To my mind there is no useful workaround.

**Closed** 2021-03-26 20:49 UTC
